<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ page import="java.util.List" %>
<%@ page import="org.apache.commons.text.StringEscapeUtils" %>
<%@ page import="com.sejong.newbluebrick.model.BoardContent" %>
<%@ page import="org.springframework.data.domain.Page" %>


<!DOCTYPE html>
<html lang="ko">
<%@ include file="/WEB-INF/jsp/common/head_eng.jsp"  %>
<body>

<div class="wrap">
    <%@ include file="/WEB-INF/jsp/common/header_eng.jsp"  %>

    <script>
    link = "${param.link}";
    </script>

	<div class="inner_mc main_visual_mc">
	    <div class="content_mc">
	        <div class="main_bg main_bg_1"><img src="<c:url value="/public/imgs/bg_1.jpg"/>" alt=""></div>
	        <div class="slogan_sp amt amt_1">
<!-- 	            <p class="t_4 ani fn--p fw--600"> Blockchain 3.0 </p> -->
	            <!-- <p class="t_1 ani fn--p fw--600">
	            	Let <span class="flag">＇</span> s Build Up the
	            								The Start of a <br> New Journey
	            </p> -->
	            <p class="t_1 ani fn--p fw--600" style="font-size:51px; margin-left:-1px; font-style: normal;">
								Connected &
	            </p>

	            <!-- <p class="t_2 ani fn--p fw--600">New Eco-system</p> -->
	            <p class="t_2 ani fn--p fw--600" style="font-size:135px; margin-left:-10px;">BlueBrick</p>
	            <div class="t_3 ani">
	                <ul class="tab fn--p fw--500">
	                    <li class="on">Assemble</li>
	                    <li>Decentralization</li>
	                    <li>Ecosystem</li>
	                </ul>
	                <ul class="exp fn--n">
				<!-- <li class="on">The “brick”, Sejong’s brand mark, represents the concentrated value and solidity of the platform, and symbolizes Sejong’s network management know-how and security technology. </li> -->
        <li class="on">Our brandmark, ‘Brick’, brings together SEJONG’s outstanding network operation know-how, security, technology, facilities, and symbolized the concentrated values and the future of out platform</li>
				<li>The values establish a service-oriented platform that enables discovery of diversified possibilities by expanding from the center and thereby realizing digital asset fluidity</li>
				<li>The new values generated by BlueBrick connect and expand on many principles, building a shared ecosystem of coexistence and freedom with its participants</li>
	                </ul>
	            </div>
	        </div>
	    </div>
	</div>

	<div class="inner_mc main_introduce_mc">

	    <div class="content_mc">
	        <div class="main_bg main_bg_1"><img src="<c:url value="/public/imgs/bg_2.jpg"/>" alt=""></div>
	        <div class="slogan_sp amt amt_2">
	            <p class="t_1 ani fn--p fw--600">Introduce to BlueBrick</p>
	            <p class="t_2 ani fn--n fw--200" style="text-align:left;">
	            <!-- <strong>BlueBrick is a service-type blockchain main net with infinite possibilities for expansion.</strong><br><br> -->
              <strong>Liquidation of Digital Asset. Value realization with BlueBrick</strong><br><br>


	            <!-- BlueBrick is an Ethereum-based blockchain main net (BaaS, Backend-as-a-Service) developed by SEJONG Telecom, a leader in wired and wireless communication with 28 years of experience. <br><br>
							BlueBrick is a multi-side chain structure, enabling indefinite expansion of the side chain with customized support for different services, exchange of internal and external coins (tokens) and DEX-format data through interexchange chains, security at the level of the finance industry, and free transaction fees. -->
              BlueBrick is the name of the brand and integrated platform of the blockchain business by SEJONG Telecom, which has been operating the telecommunication business for the past 30 years, 
              is focusing on. Our BlueBrick technology is aimed to create diverse values and infinite possibility of potentials and is applying into diverse industries, such as real estates, data, and supply chain. Especially, 
              we are implementing to the ultimate goal of co-economic platform to make a value creation and trust as well as we will prepare the foundation of financial ecosystem to create a digital assets can be traded through the Special Regulatory Free Zone in BUSAN.


	            </p>
	        </div>

	        <div class="info_sp amt amt_3">
	            <ul class="view">
	                <li class="on">
	                    <h3 class="num">01.</h3>
	                    <p class="title">Brand Story</p>
	                    <!-- <p class="exp"> -->
	                    	<!--
                        Bluebrick is a BaaS-type main net, whose multi-side chain design offers competitive advantages in its expandability, speed, security, stability, economic efficiency, and compatibility. <br><br>
                        BlueBrick’s multi-side chain structure can expand infinitely by being able to add parallel side chains; it also provides individualized support for the needs of its participants and partners.<br><br>
                        Bluebrick aspires to become an economic platform based on shared values and the ability to coexist, while also building and pioneering businesses based on the same system.
                         -->
                        <br>The values created by BlueBrick are extended and distributed, enabling the liquidity of digital assets, connecting and expanding indefinitely.<br>
	                    <p class="logo" style="margin-top:20px"><img src="<c:url value="/public/imgs/introduce_logo.png"/>" alt=""></p>

	                    <div class="exp">
	                        <div class="l_sp">
	                            <h4>Blue</h4>
	                            <p style="text-align:left;"><font size="3">Blue is an expression of stability, reliability, sincerity, and responsibility.</font></p>
	                        </div>
	                        <span class="ic-sets ty1-3"></span>
	                        <div class="l_sp">
	                            <h4>Brick</h4>
	                            <p style="text-align:left;"><font size="3">Brick is a symbol of a block, which is the basic unit of blockchain.</font></p>
	                        </div>
	                    </div>
	                    <button type="button" class="btn_close"></button>
	                </li>

	                <li>
	                    <h3 class="num">02.</h3>
	                    <p class="title">BlueBrick technology</p>
	                    <p class="exp" style="text-align:left;"><font size="3">
	                    	<!-- Bluebrick is an expression of Sejong’s pride and accountability with its advanced technology. BlueBrick is also realizing the concentrated value and potential of SEJONG Telecom’s own blockchain technology. <br><br>
                        Each block has stable and precise time-stamp technology, and can expand and connect to other blocks just like building blocks, symbolizing the function and goal of service, which is to increase the value of client assets. Ultimately, SEJONG Telecom and its participants will create a new economic ecosystem that will be shared where everyone will benefit from its prosperity. -->
                        BlueBrick platform is offered the current most utilized solution, Ethereum and HyperLedger Fabric, and allows to choose the services customer want to implement. <br><br>
                        Ethereum-based platform is unlimited expandable and service-oriented private mainnet, capable of decentralized processing through multiple sidechain for each service. It offers differentiated competitiveness in scalability, compatibility, speed, and reliability, thanks to parallel processing of transaction by structural decentralization. <br><br>
                        HyperLedger Fabric solution is provided by package, including enterprise, middle wares, fabric tool and monitoring tools that helps customer to leverage into business.

						</font>
	                    </p>
	                    <button type="button" class="btn_close"></button>
	                </li>

	                <li>
	                    <h3 class="num">03.</h3>
	                    <p class="title">Core value</p>
	                    <p class="exp" style="text-align:left;"> <font size="3">
	                    	
                        With SEJONG’s blockchain business and the cutting-edge network technology, “BlueBrick” is aimed to create diverse values and infinite possibility of potential and to build a sharing economy with all participants. <br><br>
                        - Business Service : To discover and commercialize new biz model, we are doing investment, consulting, marketing and infrastructure supports for our partners to let in BlueBrick eco-system. <br><br>
                        - Government : We are also verifying and commercializing blockchain technology and tasks through collaborating with local governments and sovereign entity.<br><br>
                        - Financial : We are creating the Blockchain-based protocol finance ecosystem that allows the inter-exchange of real & digital(crypto) assets.

						</font>
	                    </p>
	                    <button type="button" class="btn_close"></button>
	                </li>

	            </ul>

	            <ul class="lst">
	                <li class="ani">
	                    <h3 class="num">01.</h3>
	                    <p class="title">Brand Story </p>
	                    <button type="button" class="ic-sets ty1-1 btn_plus"></button>
	                </li>
	                <li class="ani">
	                    <h3 class="num">02.</h3>
	                    <p class="title">Mainnet</p>
	                    <button type="button" class="ic-sets ty1-1 btn_plus"></button>
	                </li>
	                <li class="ani">
	                    <h3 class="num">03.</h3>
	                    <p class="title">The value of BlueBrick</p>
	                    <button type="button" class="ic-sets ty1-1 btn_plus"></button>
	                </li>
	            </ul>
	        </div>
	    </div>

	</div>


	<div class="inner_mc main_advantages_mc">

	    <div class="main_ad_mc fn--p">

	        <div class="lst amt amt_3">
	            <ul>
	                <li class="ani">
	                    <div class="cont">
	                        <p class="ic"><img src="<c:url value="/public/imgs/ad_ic_1.png"/>" alt=""></p>
	                        <p class="txt fw--500">Digital Asset Trading</p>
	                        <button type="button" class="btn_more btn-sets ty1-4 aft fw--600">More</button>
	                    </div>
	                    <div class="exp">
	                        <dl>
                                <!-- <dt>Redistribution of wealth in fairly by tokenizing asset</dt>
                                <dd><p>Real estate, ship finance, aircraft leasing, expensive artwork, etc</p></dd>
                                <dd><p>P2P trading with tokenized asset</p></dd><br>
                                <dt>Real estate Collective investment</dt>
                                <dd><p>Creating public offering funds to invest into real estates, Offering experience of easy investment to everyone</p></dd>
								<dd><p>Issuing digital certificates of entitlements, ensuring reliability</p></dd>
								<dd><p>Fast and active multilateral  transaction, reducing remittance fee</p></dd>
								<dd><p>The economic function by activating real-estate public offering funds</p></dd> -->

				<dt>Reorganization of fair wealth by tokenizing assets</dt>
	                	<dd><p>Real estate, ships, aircraft, expensive artworks, etc.</p></dd>
	                	<dd><p>Free transactions between individuals through tokenization of assets</p></dd><br>
	                	<dt>Real estate collective investment and revenue allocation services</dt>
	                	<dd><p>Creating a public offering fund to invest in real estate items, easy and convenient investment experience for many</p></dd>
	                	<dd><p>Real estate fund beneficiary certificates trading is possible through the blockchain-based platform</p></dd>
	                	<dd><p>Matching beneficiary certificates with blockchain-based digital certificates</p></dd>
	                	<dd><p>Fast, active multilateral transactions, reduced commission fees</p></dd>
	                	<dd><p>Invigorating real estate public offering funds for the proper functioning of an economy</p></dd>
                            </dl>
	                        <button type="button" class="btn_close ic-sets ty1-2"></button>
	                    </div>
	                </li>
	                <li class="ani">
	                    <div class="cont">
	                        <p class="ic"><img src="<c:url value="/public/imgs/ad_ic_2.png"/>" alt=""></p>
	                        <p class="txt fw--500">MyData</p>
	                        <button type="button" class="btn_more btn-sets ty1-4 aft fw--600">More</button>
	                    </div>
	                    <div class="exp">
	                        <dl>
                                <dt>Medical MyData Platform</dt>
                                <dd><p>Efficient management of Medical data(Electronic prescription, issuing proof application forms, one-stop insurance claim, etc)</p></dd>
								<dd><p>Contributing to medical industry development by providing 'My Medical/Health data' to college, pharmaceutical company, labs, etc</p></dd>
								<dd><p>Providing a variety of rewards such as digital voucher compensation</p></dd>

                                <dt>SER: Smart Education Record</dt>
                                <dd><p>Tracking history and certificate of academic information and recovery missing data</p></dd>
								<dd><p>Securing data reliability and offering education history verification effectively (diploma/certificate/transcript, etc)</p></dd>
								<dd><p>Applying non-formal education and empowerment education program as well as regular academic curriculum</p></dd>
                            </dl>
	                        <button type="button" class="btn_close ic-sets ty1-2"></button>
	                    </div>
	                </li>
	                <li class="ani">
	                    <div class="cont">
	                        <p class="ic"><img src="<c:url value="/public/imgs/ad_ic_3.png"/>" alt=""></p>
	                        <p class="txt fw--500">Supply Chain</p>
	                        <button type="button" class="btn_more btn-sets ty1-4 aft fw--600">More</button>
	                    </div>
	                    <div class="exp">
	                        <dl>
                              	<dt>Agricultural, Fisheries and Foods production and circulation service</dt>
                              	<dd><p>Real-time tracking and monitoring in supply chain management</p></dd>
								<dd><p>Data authentication & integrity verification to prevent fraud</p></dd>
								<dd><p>Smart direct transaction between producers and consumers</p></dd>
								<br>

                              <dt>Veterinary Records Management</dt>
                              <dd><p>Veterinary records and life management to establish a good culture of companion animal</p></dd>
                              <dd><p>Connecting total care services (health, medical, food, etc)</p></dd>
                          </dl>
	                        <button type="button" class="btn_close ic-sets ty1-2"></button>
	                    </div>
	                </li>
	                <li class="ani">
	                    <div class="cont">
	                        <p class="ic"><img src="<c:url value="/public/imgs/ad_ic_4.png" />" alt=""></p>
	                        <p class="txt fw--500">BaaS</p>
	                        <button type="button" class="btn_more btn-sets ty1-4 aft fw--600">More</button>
	                    </div>
	                    <div class="exp">
	                        <dl>
                                <dt>BaaS platform & BlueBrick ecosystem</dt>
                                <dd><p>Offering customized enterprise solution based on HyperLedger Fabric </p></dd>
								<dd><p>Implementing Blockchain technology in a short period, at a reasonable costs, without own technology</p></dd>
								<dd><p>Increasing security, automation and efficiency</p></dd>
								                                

                            </dl>
	                        <button type="button" class="btn_close ic-sets ty1-2"></button>
	                    </div>
	                </li>
	                <li class="ani">
	                    <div class="cont">
	                        <p class="ic"><img src="<c:url value="/public/imgs/ad_ic_5.png" />" alt=""></p>
	                        <p class="txt fw--500">DeFi</p>
	                        <button type="button" class="btn_more btn-sets ty1-4 aft fw--600">More</button>
	                    </div>
	                    <div class="exp">
	                        <dl>
                                <dt>Defi Trading Platform for crypto-asset</dt>
                                <dd><p>Establishing B2B transaction to exchange stable coin</p></dd>
								<dd><p>Expanding financing service of digital assets (transfer, credit, custody, loan, etc)</p></dd>
                                
                            </dl>
	                        <button type="button" class="btn_close ic-sets ty1-2"></button>
	                    </div>
	                </li>
	            </ul>
	        </div>

	        <!-- <div class="view">
	            <ul>
	                <li class="on">

	                    <div class="exp fn--n">
	                        <dl>
	                            <dt> 거래 수수료 무료정책 </dt>
	                            <dd> 신규 블록체인 비즈니스 적용에 유리 </dd>
	                        </dl>

	                        <dl>
	                            <dt>Web/App 지갑 및 블록체인 explorer 지원</dt>
	                            <dd>파트너사가 비즈니스에만 전념할 수 있게 통합된 Wallet 및 explorer 지원</dd>
	                        </dl>

	                        <dl>
	                            <dt>파트너사 기술지원</dt>
	                            <dd>비즈니스 DAPP 개발 기술 지원</dd>
	                            <dd>개발 편의를 위한 API 제공</dd>
	                        </dl>
	                    </div>
	                </li>
	            </ul>
	            <button type="button" class="btn_close ic-sets ty1-2"></button>
	        </div> -->
	    </div>

	    <div class="content_mc">
	        <ul class="other">
	            <li>
	                <div class="trans_bg"><img src="<c:url value="/public/imgs/wallet_bg.jpg"/>" alt="bbrick"></div>
                        <div class="amt amt_4" style="cursor: pointer;" onclick="location.href='https://bbric.com/';">   
			    <p class="ani"></p><p class="ani"></p><p class="ani"></p>
	                    <p class="ani"></p><p class="ani"></p><p class="ani"></p>
	                    <p class="ani"></p><p class="ani"></p><p class="ani"></p>
	                </div>
<!--
	               <a href="https://www.bluebrick.io/wallet/intro" target="_blank" class="btn fn--p">
	                   <span class="t_1">Other business </span>
	                   <span class="t_2 fw--500">BlueBrick <br>Wallet</span>
	                   <span class="ic-sets"></span>
	               </a>
-->
	            </li>

	            <li>
			<div class="trans_bg"><img src="<c:url value="/public/imgs/scan_bg.jpg" />" alt="bhealth"></div>
                       <div class="amt amt_4" style="cursor: pointer;" onclick="location.href='https://www.bhealthy.co.kr/';">
	                    <p class="ani"></p><p class="ani"></p><p class="ani"></p>
	                    <p class="ani"></p><p class="ani"></p><p class="ani"></p>
	                    <p class="ani"></p><p class="ani"></p><p class="ani"></p>
	               </div>
<!--
	               <a href="https://scan.bluebrick.io/scanweb/main" target="_blank" class="btn fn--p">
	                   <span class="t_1">Other business </span>
	                   <span class="t_2 fw--500">BlueBrick <br>Scan</span>
	                   <span class="ic-sets"></span>
	               </a>
-->
	            </li>

	        </ul>
	    </div>

	</div>


	<div class="inner_mc main_news_mc">

	    <div class="content_mc">
	        <div class="main_bg main_bg_2"><img src="<c:url value="/public/imgs/bg_4.png" />" alt=""></div>
	        <div class="lst amt amt_3">
	            <ul>

	                <li class="ani">
	                    <a href="<c:url value="/news/view/?lang=${param.lang}&num=${mainNewsFirst.itemNumber }"/>">
	                    	<c:if test="${empty mainNewsFirst.tumbnailPath}">
	                    		<span class="thumb"><img src="<c:url value="/public/imgs/news/temp.png" />" alt=""></span>
	                    	</c:if>
	                    	<c:if test="${not empty mainNewsFirst.tumbnailPath}">
	                    		<span class="thumb"><img src="<c:url value="/uploadFile/${mainNewsFirst.tumbnailPath }" />" alt=""></span>
	                    	</c:if>
	                        <span class="sort">news </span>
	                        <span class="title">${mainNewsFirst.subject } </span>
	                        <span class="ic-sets ty2-3"></span>
	                    </a>
	                </li>
	                <li class="ani center">
	                    <a href="<c:url value="/notice/view/?lang=${param.lang}&num=${mainNoticeFirst.itemNumber }"/>">
	                        <span class="thumb"><img src="<c:url value="/public/imgs/news/temp.png" />" alt=""></span>
	                        <span class="sort">notice</span>
	                        <span class="title">${mainNoticeFirst.subject }</span>
	                        <span class="ic-sets ty2-2"></span>
	                    </a>
	                </li>
	                <li class="ani">
	                    <a href="<c:url value="/news/view/?lang=${param.lang}&num=${mainNewsSecond.itemNumber }"/>">
	                        <c:if test="${empty mainNewsSecond.tumbnailPath}">
	                    		<span class="thumb"><img src="<c:url value="/public/imgs/news/temp.png" />" alt=""></span>
	                    	</c:if>
	                    	<c:if test="${not empty mainNewsSecond.tumbnailPath}">
	                    		<span class="thumb"><img src="<c:url value="/uploadFile/${mainNewsSecond.tumbnailPath }" />" alt=""></span>
	                    	</c:if>
	                        <span class="sort">news </span>
	                        <span class="title">${mainNewsSecond.subject }</span>
	                        <span class="ic-sets ty2-3"></span>

	                    </a>
	                </li>
	            </ul>
	        </div>

	    </div>

	</div>



	<div class="inner_mc main_technique_mc">
	        <div class="content_mc">
	            <div class="thumb"><img src="<c:url value="/public/imgs/thumb_4_1.jpg" />" alt=""></div>
	            <div class="slogan_sp amt amt_2" style="width: 42%;">
	                <p class="t_1 ani fn--p fw--600">BlueBrick Technology</p>
	                <p class="t_2 ani fn--n fw--200" style="margin-top: 20px;">

	                    <!-- BlueBrick은 무한 확장이 가능한 서비스 별 맞춤형 'Private <br>
	                    BlockChain'입니다.  BlueBrick은 서비스 별 멀티체인을 통해 분산<br>
	                    처리가 가능하며 Inter-ExchangeChain Chain을 통해  분산처리 된 정보를<br>
	                    서로 교환할 수 있습니다. 서비스 중심의 블록체인인 BlueBrick은<br>
	                    구조적 분산화로 트랜잭션이 병렬 처리되어 빠른 속도를 보장하며 서비스<br>
	                    특성에 맞는 블록체인 구성에 효과적입니다. 블록 생성주기는 1초로써<br>
	                    대용량 TPS가 필요한 파트너사의 니즈에 모든 맞춤형 지원이 가능하고 <br>
	                    역삼, 분당, 부산 등 자체 보유한 IDC를 바탕으로 광대역 내/외부 네트워크<br>
	                    및 Network APT, Layer 7 Switch 등 최첨단 보안 설비로 금융권 수준의<br>
	                    보안 인프라를 지원하여 블록체인의 보안 및 안정성을 보장합니다. -->

	                    <!-- BlueBrick is a customized type of 'Private Blockchain' for each service and is capable of unlimited expansion. BlueBrick is capable of decentralized processing through multi-chains for each service and decentralized data can be exchanged through the Inter-Exchange Chain. BlueBrick, which is a service-oriented blockchain, guarantees high speeds due to parallel processing of transactions by means of structural decentralization, and effectively creates blockchain suitable for service. With a block generation cycle of 1 second, BlueBrick is capable of providing customized support for all partner companies needing large capacity TPS. Moreover, it supports a security infrastructure at the level of the financial sector by means of a broadband internal/external network and the most advanced security applications, such as Network APT and Layer 7 Switch, etc., along with independently held IDC in Yeoksam, Bundang, and Busan. As such, we guarantee the security and stability of the blockchain. -->


	                    <!-- <strong>Bluebrick is a ‘private blockchain’ service<br> that can be  expanded infinitely. </strong> <br><br>-->
                      <strong><font size="5">Co-Creation for Connectivity Ecosystem</font></strong><br><br>
                     
										<!-- Bluebrick can perform distributed processing via service-specific multi-chains; exchange of processed information is possible through inter-exchange chain.<br>
                    The structural distribution enables quick parallel processing of transactions, with efficient blockchain design that fits each service’s needs.<br>
                    Block generation cycle is 1 second, and customized support is provided for client-specific needs, including large volume TPS.<br>
                     The internal data centers located in Yeoksam, Bundang, and Busan assure stable and secure blockchain services with cutting-edge infrastructure, including broadband internal/external network, network APT, layer 7 switch and other security features at the level required by the financial industry. -->
                    BlueBrick platform is built on major open source tools such as Ethereum and HyperLedger Fabric. It is provided the infrastructure needed for enterprise solution development, operation and governance. To apply into financial, process innovation and regulatory reform, we are working on the development of platform and dApps based on BlueBrick technology.<br><br>
					BlueBrick is aimed for a BaaS(Blockchain as a Service) platform for practical use. The company struggling new technology due to time and expenses can implement this blockchain solution easily and conveniently to existing business at a reasonable cost in a short period of time. It is also facilitates verification of various business projects, including public, financial, distribution, document management, 
					and proof. We are trying to apply blockchain to various areas, co-create new value and drive changes with all our customers and participants in the eco-system.
	                </p>

<!--
 /newbluebrick/technical?lang=&
 /newbluebrick/technical?lang=&link=technique
/newbluebrick/?lang=&link=technique
 -->
	                <a href="<c:url value="/technical?lang=${param.lang }&"/>" class="ani btn_arrow ic-sets ty2-4" style="margin-top: 10px;"></a>
	            </div>
	        </div>
	</div>

	<!-- <div class="inner_mc main_token_mc">
	    <div class="content_mc">
	        <div class="thumb"><img src="<c:url value="/public/imgs/thumb_4_2.jpg"/>" alt=""></div>
	        <div class="slogan_sp amt amt_2">
	            <p class="t_1 ani fn--p fw--600">BlueBrick<br>Token Policy</p>
	            <p class="t_2 ani fn--n fw--200">
	                BlueBrick 토큰정책 관련 내용을 표기하는 부분입니다. BlueB<br>
	                rick 토큰정책 관련 내용을 표기하는 부분입니다. BlueBrick 토<br>
	                큰정책 관련 내용을 표기하는 부분입니다. BlueBrick 토큰정책 <br>
	                관련 내용을 표기하는 부분입니다.
	            </p>
	            <a href="#" class="ani btn_arrow ic-sets ty2-2"></a>
	        </div>
	    </div>
	</div> -->

    <%@ include file="/WEB-INF/jsp/common/footer_eng.jsp"  %>
<%--     <%@ include file="/WEB-INF/jsp/common/youtube_pop.jsp"  %> --%>


</div>



</body>
</html>
