<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ page import="java.util.List" %>
<%@ page import="org.apache.commons.text.StringEscapeUtils" %>
<%@ page import="com.sejong.newbluebrick.model.BoardContent" %>
<%@ page import="org.springframework.data.domain.Page" %>


<!DOCTYPE html>
<html lang="ko">
<%@ include file="/WEB-INF/jsp/common/head_m_eng.jsp"  %>
<body>

<div class="wrap">
    <%@ include file="/WEB-INF/jsp/common/header_m_eng.jsp"  %>

<script>
 link = "${param.link}";
</script>

    <div class="inner_mc main_visual_mc scroll_top">
        <div class="content_mc">
            <div class="main_bg main_bg_1"><img src="<c:url value="/public/imgs/m/bg_1.jpg"/>" alt=""></div>
            <div class="slogan_sp amt amt_2">
<!--                 <p class="t_4 ani fn--p fw--600">Blockchain 3.0</p> -->
                <p class="t_1 ani fn--p fw--600" style="font-size: 50px; margin-left:-1px; font-style: normal;">Connected & </p>
                <p class="t_2 ani fn--p fw--600" style="font-size: 80px;">BlueBrick</p>
                
                
                <div class="t_3 ani">
                    <ul class="tab fn--p fw--500">
                        <li class="on">Assemblie</li>
                        <li>Decentralization</li>
                        <li>Ecosystem</li>
                    </ul>
                    <ul class="exp fn--n">
                        <!-- <li class="on">Brick, a Sejong brand, brings together Sejong’s <br>outstanding  network operation technology  and <br>symbolizes the key values and future of our platform.</li>
                        <li>These values establish a platform that enables <br>discovery of diversified possibilities by expanding from<br> the center and thereby realizing digital asset fluidity.</li>
                        <li>BlueBrick’s values are ultimately generating a new <br>ecosystem of sharing and coexistence by connecting<br> and expanding various principles.</li> -->

                        <!-- <li class="on">'Brick', icon of BlueBrick, brings together SEJONG's outstanding<br> network operation know-how,  technology, and facilities<br> and symbolized the key values and the future of our platform </li>
                        <li>The values establish a service-oriented platform<br>that enables discovery of diversified possibilities by expanding<br> from the center and thereby realizing digital asset fluidity</li>
                        <li>BlueBrick's values are ultimately generating a new<br> eco-system of sharing and co-existence by connecting<br> and expanding various principals</li> -->
                        <!-- <li class="on">The “brick”, Sejong’s brand mark, represents the concentrated <br>value and solidity of the platform, and symbolizes Sejong’s <br>network management know-how and security technology. </li> -->
                        <li class="on">Our brandmark, ‘Brick’, brings together SEJONG’s outstanding network operation know-how, security, technology, facilities, and symbolized the concentrated values and the future of out platform</li>
                        <li>The values establish a service-oriented platform that enables <br>discovery of diversified possibilities by expanding from <br>the center and thereby realizing digital asset fluidity</li>
                        <li>The new values generated by BlueBrick connect and expand on <br>many principles, building a shared ecosystem of coexistence <br>and freedom with its participants</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="inner_mc main_introduce_mc">

        <div class="content_mc">
            <div class="main_bg main_bg_1"><img src="<c:url value="/public/imgs/m/bg_2.jpg"/>" alt=""></div>
            <div class="slogan_sp amt amt_2">
                <p class="t_1 ani fn--p fw--600">Introduce to BlueBrick</p>
                <p class="t_2 ani fn--n fw--200" style="padding:0 calc(20/1080*100vw);">
                    <!-- This blockchain mainnet & DApp service exhibits key values and possibilities by bringing together Sejong’s outstanding network operation technology into block.
                    BlueBrick’s values establish a new ecosystem of freedom and coexistence with its participants by connecting and expanding various principles. -->

                    <!-- <strong>BlueBrick is a service-type blockchain main net with infinite possibilities for expansion.</strong><br><br> -->
                    <!-- <strong>Unlimited expandable &amp; Service - oriented Private Blockchain Main-net</strong><br><br> -->
                    <strong>Liquidation of Digital Asset. Value realization with BlueBrick</strong><br><br>
                    <!-- BlueBrick is an Ethereum-based blockchain main net (BaaS, Backend-as-a-Service)
                    developed by SEJONG Telecom, a leader in wired and wireless communication with 28 years  ... -->
                     <!-- BlueBrick is an Ethereum-based private main-net in the form of BaaS(Blockchain-as-a-Service) developed by SEJONG Telecom, a leader of integrated telecommunication carrier with 28 years of experiences... -->
                    BlueBrick is the name of the brand and integrated platform of the blockchain business by SEJONG Telecom, which has been operating the telecommunication business for the past 30 years, 
              is focusing...
                    <!-- BlueBrick is capable of decentralized processing through Multiple SideChain for each service, decentralized internal and external data and coin/token can be exchanged through the Inter-Exchange Chain, security at the level of the finance industry, and free transaction fees. -->

                     <!--of experience.<br><br>
                    BlueBrick is a multi-side chain structure, enabling indefinite expansion of the side chain with customized support for different services, exchange of internal and external coins (tokens) and DEX-format data through interexchange chains, security at the level of the finance industry, and free transaction fees. -->
                </p>
            </div>

            <div class="info_sp amt amt_3">
                <!-- <ul class="view">
                    <li class="on">
                        <h3 class="num">01.</h3>
                        <p class="title">블록체인 플랫폼의 특징</p>
                        <p class="exp">
                            세종텔레콤의 통신 인프라와 자체 개발한 메인넷을 기반으로 실제 <br>
                            비즈니스에 적용할 수 있도록 확장 가능한 블록체인 플랫폼입니다. <br><br>
                            다양한 분야에 접목하고 참여를 원하는 업체와 공동 비즈니스를 개척해 <br>
                            나갈 수 있는 나눔과 상생의 경제 플랫폼이 되기를 추구합니다.
                        </p>
                        <button type="button" class="btn_close"></button>
                    </li>

                    <li>
                        <h3 class="num">02.</h3>
                        <p class="title">블루브릭의 가치</p>
                        <p class="exp">
                            세종의 뛰어난 네트워크 운영기술에 대한 자신감과 책임감에 대한 <br>
                            표현이기도하며 세종텔레콤이 직접 연구∙개발한 우수한 블록체인 기술을<br>
                            블록으로 함축시켜 응축된 가치와 가능성을 펼쳐냅니다.<br><br>
                            각 블록별로 안정적이고 정확한 타임스탬프 기록 기술을 구현하며 마치<br>
                            블록을 쌓듯 여러 주체를 연결하고 확장하고(=신규 비즈니스 확장) 벽돌을<br>
                            안정감 있게 쌓아감으로써 플랫폼 이용고객의 자산가치를 높이는 기능과<br>
                            서비스 목표에 의미를 부여했습니다.궁극적으로는 세종텔레콤과 참여자가<br>
                            나누고 상생하는 새로운 경제 생태계를 만들어가게 됩니다.
                        </p>
                        <button type="button" class="btn_close"></button>
                    </li>

                    <li>
                        <h3 class="num">03.</h3>
                        <p class="title">블루브릭의 의미</p>
                        <p class="logo"><img src="<c:url value="/public/imgs/m/introduce_logo.png"/>" alt=""></p>

                        <div class="exp">
                            <div class="l_sp">
                                <h4>Blue</h4>
                                <p>안정, 신뢰, 진심, 책임감 등을 표현 </p>
                            </div>
                            <span class="ic-sets ty1-3"></span>
                            <div class="l_sp">
                                <h4>Brick</h4>
                                <p>블록체인의 기본 단위인 블록을 벽돌(Brick)로 표현</p>
                            </div>
                        </div>
                        <button type="button" class="btn_close"></button>
                    </li>

                </ul> -->

                <ul class="lst">
                    <li class="ani">
                        <h3 class="num">01.</h3>
                        <p class="title">Brand Story</p>
                        <button type="button" class="ic-sets ty1-1 btn_plus"></button>
                        <a class="cover" href="<c:url value="/introduce/?cont=content_2&lang=${param.lang }"/>"></a>
                    </li>
                    <li class="ani">
                        <h3 class="num">02.</h3>
                        <p class="title">Mainnet</p>
                        <button type="button" class="ic-sets ty1-1 btn_plus"></button>
                        <a class="cover" href="<c:url value="/introduce/?cont=content_3&lang=${param.lang }"/>"></a>
                    </li>
                    <li class="ani">
                        <h3 class="num">03.</h3>
                        <p class="title">The value of BlueBrick</p>
                        <button type="button" class="ic-sets ty1-1 btn_plus"></button>
                        <a class="cover" href="<c:url value="/introduce/?cont=content_4&lang=${param.lang }"/>"></a>
                    </li>
                </ul>
            </div>
        </div>

    </div>


    <div class="inner_mc main_advantages_mc">

        <div class="main_ad_mc fn--p">

            <div class="jx-slider" id="jx-slider-ad">

                 <div class="jx-box lst">
                       <ul class="jx-wrap">
                             <li class="jx-unit">
                                <a class="jx-cont cont" href="<c:url value="/advantage/?cont=content_1&lang=${param.lang }"/>">
                                    <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_1.png"/>" alt=""></p>
                                    <p class="txt fw--500">Digital Asset...</p>
                                    <p class="btn_more btn-sets ty1-3 aft fw--600" href="">More</p>
                                 </a>
                             </li>
                             <li class="jx-unit">
                                <a class="jx-cont cont" href="<c:url value="/advantage/?cont=content_2&lang=${param.lang }"/>">
                                    <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_2.png"/>" alt=""></p>
                                    <p class="txt fw--500">MyData</p>
                                    <p class="btn_more btn-sets ty1-3 aft fw--600" href="">More</p>
                                </a>
                             </li>
                             <li class="jx-unit">
                                <a class="jx-cont cont" href="<c:url value="/advantage/?cont=content_3&lang=${param.lang }"/>">
                                    <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_3.png"/>" alt=""></p>
                                    <p class="txt fw--500">Supply Chain<!--  / STABILITY --></p>
                                    <p class="btn_more btn-sets ty1-3 aft fw--600" href="">More</p>
                                </a>
                             </li>
                             <li class="jx-unit">
                                <a class="jx-cont cont" href="<c:url value="/advantage/?cont=content_4&lang=${param.lang }"/>">
                                    <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_4.png"/>" alt=""></p>
                                    <p class="txt fw--500">BaaS</p>
                                    <p class="btn_more btn-sets ty1-3 aft fw--600" href="">More</p>
                                </a>
                             </li>
                             <li class="jx-unit">
                                <a class="jx-cont cont" href="<c:url value="/advantage/?cont=content_5&lang=${param.lang }"/>">
                                    <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_5.png"/>" alt=""></p>
                                    <p class="txt fw--500">DeFi</p>
                                    <p class="btn_more btn-sets ty1-3 aft fw--600" href="">More</p>
                                </a>
                             </li>

                       </ul>
                 </div>

            </div>


            <!-- <div class="lst  ">
                <ul>
                    <li class="">
                        <div class="cont">
                            <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_1.png"/>" alt=""></p>
                            <p class="txt fw--500">SCALABILTY</p>
                            <button type="button" class="btn_more btn-sets ty1-3 aft fw--600">More</button>
                        </div>

                    </li>
                    <li class="">
                        <div class="cont">
                            <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_2.png"/>" alt=""></p>
                            <p class="txt fw--500">SPEED</p>
                            <button type="button" class="btn_more btn-sets ty1-3 aft fw--600">More</button>
                        </div>

                    </li>
                    <li class="">
                        <div class="cont">
                            <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_3.png"/>" alt=""></p>
                            <p class="txt fw--500">SECURITY / STABILITY</p>
                            <button type="button" class="btn_more btn-sets ty1-3 aft fw--600">More</button>
                        </div>

                    </li>
                    <li class="">
                        <div class="cont">
                            <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_4.png"/>" alt=""></p>
                            <p class="txt fw--500">ECONMICAL</p>
                            <button type="button" class="btn_more btn-sets ty1-3 aft fw--600">More</button>
                        </div>

                    </li>
                    <li class="">
                        <div class="cont">
                            <p class="ic"><img src="<c:url value="/public/imgs/m/ad_ic_5.png"/>" alt=""></p>
                            <p class="txt fw--500">COMPATIBILITY</p>
                            <button type="button" class="btn_more btn-sets ty1-3 aft fw--600">More</button>
                        </div>
                        <div class="exp">
                            <dl>
                                <dt>Inter-ExchangeChain</dt>
                                <dd>내부 토큰 간의 교환 기능 지원</dd>
                                <dd>향후 외부 블록체인 코인 및 토큰과의 교환 기능 지원(예정)</dd>
                            </dl>
                            <button type="button" class="btn_close ic-sets ty1-2"></button>
                        </div>
                    </li>
                </ul>
            </div> -->

            <!-- <div class="view">
                <ul>
                    <li class="on">

                        <div class="exp fn--n">
                            <dl>
                                <dt> 거래 수수료 무료정책 </dt>
                                <dd> 신규 블록체인 비즈니스 적용에 유리 </dd>
                            </dl>

                            <dl>
                                <dt>Web/App 지갑 및 블록체인 explorer 지원</dt>
                                <dd>파트너사가 비즈니스에만 전념할 수 있게 통합된 Wallet 및 explorer 지원</dd>
                            </dl>

                            <dl>
                                <dt>파트너사 기술지원</dt>
                                <dd>비즈니스 DAPP 개발 기술 지원</dd>
                                <dd>개발 편의를 위한 API 제공</dd>
                            </dl>
                        </div>
                    </li>
                </ul>
                <button type="button" class="btn_close ic-sets ty1-2"></button>
            </div> -->
        </div>

        <div class="content_mc">
            <ul class="other">
                <li>
		    <div class="trans_bg"><img src="<c:url value="/public/imgs/m/wallet_bg.jpg"/>" alt="bbrick"></div>
                    <div class="amt amt_4" style="cursor: pointer;" onclick="location.href='https://bbric.com/';">
                        <p class="ani"></p><p class="ani"></p><p class="ani"></p>
                        <p class="ani"></p><p class="ani"></p><p class="ani"></p>
                        <p class="ani"></p><p class="ani"></p><p class="ani"></p>
                    </div>
<!--
                   <a class="btn fn--p" href="https://www.bluebrick.io/wallet/intro" target="_blank">
                       <span class="t_1">Other business </span>
                       <span class="t_2 fw--500">BlueBrick <br>Wallet</span>
                       <span class="ic-sets"></span>
                   </a>
-->
                </li>

                <li>
		    <div class="trans_bg" style="margin-bottom:-50%"><img src="<c:url value="/public/imgs/m/scan_bg.jpg"/>" alt="bhealth"></div>
                   <div class="amt amt_4" style="cursor: pointer; top: -100%;" onclick="location.href='https://www.bhealthy.co.kr/';">
                        <p class="ani"></p><p class="ani"></p><p class="ani"></p>
                        <p class="ani"></p><p class="ani"></p><p class="ani"></p>
                        <p class="ani"></p><p class="ani"></p><p class="ani"></p>
                   </div>
<!--
                   <a class="btn fn--p" href="https://scan.bluebrick.io/scanweb/main" target="_blank">
                       <span class="t_1">Other business </span>
                       <span class="t_2 fw--500">BlueBrick <br>Scan</span>
                       <span class="ic-sets"></span>
                   </a>
-->
                </li>

            </ul>
        </div>

    </div>


    <div class="inner_mc main_news_mc">

        <div class="content_mc">
            <!-- <div class="main_bg main_bg_2"><img src="<c:url value="/public/imgs/m/bg_4.png"/>" alt=""></div> -->
            <div class="lst amt amt_3">
                <ul>

                    <li class="ani center">
                        <a href="<c:url value="/notice/view/?num=${mainNoticeFirst.itemNumber }&lang=${param.lang }"/>">
                            <span class="thumb"><img src="<c:url value="/public/imgs/m/news/temp2.png"/>" alt=""></span>
                            <span class="sort">notice</span>
                            <!-- <span class="title">${mainNoticeFirst.subject }</span> -->
                            <span class="title">[보도자료] ﻿﻿세종텔레콤 컨소시엄, 부산 블록체인 특구 사업자로 최종 선정 (2020.07.07)</span>
                            <span class="ic-sets ty2-1"></span>
                        </a>
                    </li>
                    <li class="ani">
                        <a href="<c:url value="/news/view/?num=${mainNewsFirst.itemNumber }&lang=${param.lang }"/>">
                        	<c:if test="${mainNewsFirst.tumbnailPath eq '' }">
                        		<span class="thumb"><img src="<c:url value="/public/imgs/m/news/temp.png" />" alt=""></span>
                        	</c:if>
                        	<c:if test="${mainNewsFirst.tumbnailPath ne '' }">
                        		<span class="thumb"><img src="<c:url value="/uploadFile/${mainNewsFirst.tumbnailPath }" />" alt=""></span>
                        	</c:if>
                            <span class="sort">news </span>
                            <span class="title">${mainNewsFirst.subject }</span>
                            <span class="ic-sets ty2-3"></span>
                        </a>
                    </li>
                <!--
                    <li class="ani">
                        <a href="<c:url value="/news/view/?num=${mainNewsSecond.itemNumber }&lang=${param.lang }"/>">
                        	<c:if test="${mainNewsSecond.tumbnailPath eq '' }">
                        		<span class="thumb"><img src="<c:url value="/public/imgs/m/news/temp.png" />" alt=""></span>
                        	</c:if>
                        	<c:if test="${mainNewsSecond.tumbnailPath ne '' }">
                        		<span class="thumb"><img src="<c:url value="/uploadFile/${mainNewsSecond.tumbnailPath }" />" alt=""></span>
                        	</c:if>
                            <span class="sort">news </span>
                            <span class="title">${mainNewsSecond.subject }</span>
                            <span class="ic-sets ty2-3"></span>
                        </a>
                    </li>
                    <li class="ani center">
                        <a href="<c:url value="/notice/view/?num=${mainNoticeSecond.itemNumber }&lang=${param.lang }"/>">
                            <span class="thumb"><img src="<c:url value="/public/imgs/m/news/temp.png"/>" alt=""></span>
                            <span class="sort">notice</span>
                            <span class="title">${mainNoticeSecond.subject }</span>
                            <span class="ic-sets ty2-3"></span>
                        </a>
                    </li>
                -->
                </ul>
            </div>

        </div>

    </div>



    <div class="inner_mc main_technique_mc">
            <div class="content_mc">
                <div class="thumb"><img src="<c:url value="/public/imgs/m/thumb_4_1.jpg"/>" alt=""></div>
                <a class="slogan_sp amt amt_2" href="<c:url value="/technical?lang=${param.lang }"/>">
                    <p class="ani btn_arrow ic-sets ty2-3"></p>
                    <p class="t_1 ani fn--p fw--600">BlueBrick Technology</p>
                    <p class="t_2 ani fn--n fw--200 dotdot">
                        <!-- <strong>Bluebrick is a ‘private blockchain’ service<br> that can be  expanded infinitely. </strong><br> -->
                        <!-- <strong>BlueBrick is an Unlimited Expandable <br>&amp; Private Main-net in the form of BaaS</strong><br>
                        BlueBrick is capable of decentralized processing through Multi-SideChain. It can be exchanged decentralized data and coin/token through Inter-Exchange Chain. Its distributed configuration enables quick parallel processing of transactions, with efficient design fits to different needs of each service. The generation cycle of block is 1 second, and customized support is provided for the partner’s needs, such as higher TPS. <br>
                        In addition, we have a cutting-edge infrastructure and facilities, including high-speed broadband network and data centers located in Seoul, Bundang, and Busan. Our security level is an equivalent level of financial sectors, including network duplex, APT solution, Layer 7 Switch and so on. -->
                        
                        <strong>Co-Creation for Connectivity Ecosystem</strong><br><br>
                        
                        BlueBrick platform is built on major open source tools such as Ethereum and HyperLedger Fabric. It is provided the infrastructure needed for enterprise solution development, operation and governance. To apply into financial, process innovation and regulatory reform, we are working on the development of platform and dApps based on BlueBrick technology.<br><br>
						BlueBrick is aimed for a BaaS(Blockchain as a Service) platform for practical use. The company struggling new technology due to time and expenses can implement this blockchain solution easily and conveniently to existing business at a reasonable cost in a short period of time. It is also facilitates verification of various business projects, including public, financial, distribution, document management, 
						and proof. We are trying to apply blockchain to various areas, co-create new value and drive changes with all our customers and participants in the eco-system.

                    </p>
                </a>
            </div>
    </div>

    <%-- <div class="inner_mc main_token_mc">
        <div class="content_mc">
            <div class="thumb"><img src="<c:url value="/public/imgs/m/thumb_4_2.jpg"/>" alt=""></div>
            <a class="slogan_sp amt amt_2" href="<c:url value="/technical?lang=${param.lang }"/>">
                <p class="ani btn_arrow ic-sets ty2-3"></p>
                <p class="t_1 ani fn--p fw--600">BlueBrick Token Policy</p>
                <p class="t_2 ani fn--n fw--200 dotdot">
                    BlueBrick 토큰정책 관련 내용을 표기하는 부분입니다. BlueB
                    rick 토큰정책 관련 내용을 표기하는 부분입니다. BlueBrick 토
                    큰정책 관련 내용을 표기하는 부분입니다. BlueBrick 토큰정책
                    관련 내용을 표기하는 부분입니다.
                </p>
            </a>
        </div>
    </div> --%>

    <%@ include file="/WEB-INF/jsp/common/footer_m_eng.jsp"  %>


</div>






</body>
</html>
